spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: mscloud-config-dev
---
spring:
  profiles: test
  application:
    name: mscloud-config-test
---
spring:
  profiles: prod
  application:
    name: mscloud-config-prod    
